/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogConfirmDelete: typeof import('./src/components/dialog/DialogConfirmDelete.vue')['default']
    DialogDelete: typeof import('./src/components/dialog/DialogDelete.vue')['default']
    DialogDeleteAll: typeof import('./src/components/dialog/DialogDeleteAll.vue')['default']
    DialogDeleteSelect: typeof import('./src/components/dialog/DialogDeleteSelect.vue')['default']
    DialogEdit: typeof import('./src/components/dialog/DialogEdit.vue')['default']
    DialogSave: typeof import('./src/components/dialog/DialogSave.vue')['default']
    FormCadastro: typeof import('./src/components/FormCadastro.vue')['default']
    FormLogin: typeof import('./src/components/FormLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sair: typeof import('./src/components/Sair.vue')['default']
    TablePessoas: typeof import('./src/components/TablePessoas.vue')['default']
    TableUsuarios: typeof import('./src/components/TableUsuarios.vue')['default']
  }
}
