/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Cadastro': RouteRecordInfo<'/Cadastro', '/Cadastro', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Pessoa': RouteRecordInfo<'/Pessoa', '/Pessoa', Record<never, never>, Record<never, never>>,
    '/pessoas/Cadastrar': RouteRecordInfo<'/pessoas/Cadastrar', '/pessoas/Cadastrar', Record<never, never>, Record<never, never>>,
    '/pessoas/Deletar': RouteRecordInfo<'/pessoas/Deletar', '/pessoas/Deletar', Record<never, never>, Record<never, never>>,
    '/pessoas/Editar': RouteRecordInfo<'/pessoas/Editar', '/pessoas/Editar', Record<never, never>, Record<never, never>>,
    '/pessoas/Index': RouteRecordInfo<'/pessoas/Index', '/pessoas/Index', Record<never, never>, Record<never, never>>,
    '/Usuario': RouteRecordInfo<'/Usuario', '/Usuario', Record<never, never>, Record<never, never>>,
  }
}
